# Generated by Django 4.0.1 on 2022-01-31 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=255)),
                ('eventLocation', models.CharField(max_length=255)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=255)),
                ('eventDescription', models.TextField()),
                ('userId', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingName', models.CharField(max_length=255)),
                ('meetingdescription', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'meetings',
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceName', models.CharField(max_length=255)),
                ('resourceType', models.CharField(max_length=255)),
                ('resourceUrl', models.URLField(blank=True, null=True)),
                ('dateEntered', models.DateField()),
                ('resourceDescription', models.TextField(blank=True, max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutesText', models.TextField(blank=True, max_length=255, null=True)),
                ('attendence', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('meetingId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.meeting')),
            ],
            options={
                'db_table': 'meetingMinutes',
            },
        ),
    ]
